# Generated by Django 4.0.1 on 2022-01-21 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('site_admin', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('synchronized_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=500)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('pushed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repositories', to='github_scraper.githubuser')),
            ],
        ),
    ]
